#include "drive.h"

BSP_ADC_FUNC(I_IN)
BSP_ADC_FUNC(V_IN)
BSP_ADC_FUNC(V_OUT)
BSP_ADC_FUNC(I_OUT)
BSP_ADC_FUNC(I_L)
BSP_ADC_FUNC(I_L1)

BSP_PWM_REG(BUCK);
BSP_PWM_REG(BUCK1);
BSP_PWM_REG(BOOST);
BSP_PWM_REG(BOOST1);
