#ifndef __BOOST_PARAMETE_H
#define __BOOST_PARAMETE_H

#define USE_PI_CONTROLLER_BASE_BOOST 1
#define BOOST_CONTROL_FREQ   40000.0f

#define BOOST_MAX_DUTY 0.85f
#define BOOST_MIN_DUTY 0.05f
#define BOOST_OUT_VREF_STEP 200.0f
#define CNT_1MS_BASE_40KHZ  ((int)BOOST_CONTROL_FREQ / 1000U)

#define VOLT_LOOP_KP 10.0f
#define VOLT_LOOP_KI 0.2f
#define CURR_LOOP_KP 10.0f
#define CURR_LOOP_KI 0.05f
#define VOLT_LIMT_UP_LOOP_KP 1.0f
#define VOLT_LIMT_UP_LOOP_KI 0.01f
#define VOLT_LIMT_DN_LOOP_KP 1.0f
#define VOLT_LIMT_DN_LOOP_KI 0.01f

#define FILTER_0P05HZ_BASE_5HZ  0.001f

#endif